hl.on("hyprland.start", function()
    hl.dispatch(hl.dsp.exec_cmd("systemctl --user start hyprpolkitagent"))
    hl.dispatch(hl.dsp.exec_cmd("wl-paste --type text --watch cliphist store"))
    hl.dispatch(hl.dsp.exec_cmd("wl-paste --type image --watch cliphist store"))
    hl.dispatch(hl.dsp.exec_cmd("qs -c noctalia-shell"))
    hl.dispatch(hl.dsp.exec_cmd("openrgb --server"))
    hl.dispatch(hl.dsp.exec_cmd("/home/barberdj/.config/hypr/scripts/rgb_sync.sh"))
end)
